package kredio;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author Yusif Taghizade
 */
public class KrediOWelcome extends javax.swing.JFrame {

    /**
     * Creates new form KrediOFrame
     */
    public KrediOWelcome() {
        initComponents();
        setVisible(true);

        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);  
        setResizable(false);  //ekran resizable
        setIconImage(new ImageIcon("img/icon.png").getImage());

        jLabel1.setIcon(new ImageIcon("img/kredo.jpg"));  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        kredit = new javax.swing.JButton();
        ipoteka = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KrediO");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Welcome to KrediO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 90));

        kredit.setBackground(new java.awt.Color(0, 0, 0));
        kredit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        kredit.setForeground(new java.awt.Color(255, 255, 255));
        kredit.setText("Kredit");
        kredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kreditActionPerformed(evt);
            }
        });
        getContentPane().add(kredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 154, 150, 40));

        ipoteka.setBackground(new java.awt.Color(0, 0, 0));
        ipoteka.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ipoteka.setForeground(new java.awt.Color(255, 255, 255));
        ipoteka.setText("İpoteka");
        ipoteka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipotekaActionPerformed(evt);
            }
        });
        getContentPane().add(ipoteka, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 212, 150, 40));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        getAccessibleContext().setAccessibleDescription("Kredit & İpoteka Hesablayıcı");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ipotekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipotekaActionPerformed
        KredioMortgage a = new KredioMortgage();
//        setVisible(false);
        a.setVisible(true);
       


    }//GEN-LAST:event_ipotekaActionPerformed

    private void kreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kreditActionPerformed

        KrediOKredit a = new KrediOKredit();
//        setVisible(false);

        a.setVisible(true);

    }//GEN-LAST:event_kreditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KrediOWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KrediOWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KrediOWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KrediOWelcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KrediOWelcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ipoteka;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton kredit;
    // End of variables declaration//GEN-END:variables

}
