package kredio;

import java.text.DecimalFormat;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

                    /**
 *
 * @author Yusif Taghizade
 */
public class KredioMortgage extends javax.swing.JFrame {

    /**
     * Creates new form KredioMortgage
     */
    public KredioMortgage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        setIconImage(new ImageIcon("img/icon.png").getImage());

        jLabel6.setIcon(new ImageIcon("img/mortgage.png"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        qiymet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        faiz = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        muddet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ilkin = new javax.swing.JTextField();
        buton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textarea = new javax.swing.JTextArea();
        qiymetbildirim = new javax.swing.JLabel();
        faizbildirim = new javax.swing.JLabel();
        muddetbildirim = new javax.swing.JLabel();
        ilkinbildirim = new javax.swing.JLabel();
        sil = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setTitle("İpoteka hesablayıcı");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Evin qiymeti (AZN)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, -1));

        qiymet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qiymetActionPerformed(evt);
            }
        });
        getContentPane().add(qiymet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Kredit faizi illik (%)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 210, -1));
        getContentPane().add(faiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Kreditin müddeti (Ay)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 210, -1));
        getContentPane().add(muddet, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("İlkin Ödeniş faizi (%)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 210, -1));

        ilkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ilkinActionPerformed(evt);
            }
        });
        getContentPane().add(ilkin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 210, -1));

        buton.setBackground(new java.awt.Color(0, 0, 0));
        buton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        buton.setForeground(new java.awt.Color(255, 255, 255));
        buton.setText("Hesabla");
        buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonActionPerformed(evt);
            }
        });
        getContentPane().add(buton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 122, -1));

        textarea.setBackground(new java.awt.Color(204, 204, 204));
        textarea.setColumns(20);
        textarea.setForeground(new java.awt.Color(255, 255, 255));
        textarea.setRows(5);
        textarea.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        textarea.setEnabled(false);
        jScrollPane1.setViewportView(textarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 360, 140));

        qiymetbildirim.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(qiymetbildirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, -1));

        faizbildirim.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(faizbildirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, -1));

        muddetbildirim.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(muddetbildirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 210, -1));

        ilkinbildirim.setForeground(new java.awt.Color(153, 0, 0));
        getContentPane().add(ilkinbildirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 210, -1));

        sil.setBackground(new java.awt.Color(0, 0, 0));
        sil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sil.setForeground(new java.awt.Color(255, 255, 255));
        sil.setText("Sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });
        getContentPane().add(sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 80, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ilkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ilkinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ilkinActionPerformed

    private void qiymetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qiymetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qiymetActionPerformed

    private void butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonActionPerformed

        String bildirim;

        if (qiymet.getText().trim().equals("")) {
            bildirim = "Qiymeti daxil edin";
            qiymetbildirim.setText(bildirim);
        } else if (!qiymet.getText().trim().chars().allMatch(Character::isDigit)
                || (Double.parseDouble(qiymet.getText().trim()) <= 0)) {

            bildirim = "Qiymeti düzgün daxil edin";
            qiymetbildirim.setText(bildirim);

        } else {
            qiymetbildirim.setText("");
        }
        try {

            if (faiz.getText().trim().equals("")) {
                bildirim = "Faizi daxil edin";
                faizbildirim.setText(bildirim);
            } else if ((Double.parseDouble(faiz.getText().trim()) <= 0)) {

            } else {
                faizbildirim.setText("");
            }

        } catch (NumberFormatException e) {

            bildirim = "Faizi düzgün daxil edin";
            faizbildirim.setText(bildirim);

        }

        if (muddet.getText().trim().equals("")) {
            bildirim = "Müddeti daxil edin";
            muddetbildirim.setText(bildirim);
        } else if (!muddet.getText().trim().chars().allMatch(Character::isDigit)
                || (Double.parseDouble(muddet.getText().trim()) <= 0)) {

            bildirim = "Müddeti düzgün daxil edin";
            muddetbildirim.setText(bildirim);

        } else {
            muddetbildirim.setText("");
        }
        try {

            if (ilkin.getText().trim().equals("")) {
                bildirim = "İlkin ödenişi daxil edin";
                ilkinbildirim.setText(bildirim);
            } else if ((Double.parseDouble(ilkin.getText().trim()) <= 0 || Double.parseDouble(ilkin.getText().trim()) > 100)) {
                bildirim = "İlkin ödenişi düzgün daxil edin";
                ilkinbildirim.setText(bildirim);

            } else {
                ilkinbildirim.setText("");
            }
        } catch (NumberFormatException e) {

            bildirim = "İlkin ödenişi düzgün daxil edin";
            ilkinbildirim.setText(bildirim);
        }

        if (qiymetbildirim.getText().trim().equals("") && faizbildirim.getText().trim().equals("")
                && muddetbildirim.getText().trim().equals("") && ilkinbildirim.getText().trim().equals("")) {

            double a = Double.parseDouble(qiymet.getText());
            double b = Double.parseDouble(faiz.getText());
            double c = Double.parseDouble(muddet.getText());
            double d = Double.parseDouble(ilkin.getText());

            double aclient = a * d / 100;
            double abank = a * (100 - d) / 100;
            double boran = b / 100;  //faiz kimi girilen deyiseni edede cevirir
            double aoran = boran / 12; //ayliq faiz orani,istifade edilmir
            double pmt0 = (abank * boran / 12);   //PMT=(a70*boran/12)/(1-(1+boran/12)^(-(c/12)*12))
            double pmt1 = (1 + boran / 12);
            double pmt2 = (-(c / 12) * 12);
            double power = Math.pow(pmt1, pmt2);
            double odenis = (pmt0 / (1 - power));
            double fb = abank * aoran;
            DecimalFormat df = new DecimalFormat("#.##");
            DecimalFormat day = new DecimalFormat("#");

            String netice = "Kreditin mebleği:" + " " + df.format(abank) + " " + "AZN" + "\n"
                    + "Kreditin müddeti:" + " " + day.format(c) + " " + "Ay" + "\n"
                    + "İlkin ödenişin mebleği:" + " " + df.format(aclient) + " " + "AZN" + "\n"
                    + "Aylıq ödeniş mebleği:" + " " + df.format(odenis) + " " + "AZN" + "\n"
                    + "Esas borc:" + " " + df.format(abank) + " " + "AZN" + "\n"
                    + "Faiz borcu:" + " " + df.format(((odenis * c) - abank)) + " " + "AZN" + "\n"
                    + "Toplam mebleğ:" + " " + df.format((odenis * c)) + " " + "AZN";

            textarea.setText(netice);

        }


    }//GEN-LAST:event_butonActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed

        qiymet.setText("");
        faiz.setText("");
        muddet.setText("");
        ilkin.setText("");


    }//GEN-LAST:event_silActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KredioMortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KredioMortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KredioMortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KredioMortgage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KredioMortgage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton;
    private javax.swing.JTextField faiz;
    private javax.swing.JLabel faizbildirim;
    private javax.swing.JTextField ilkin;
    private javax.swing.JLabel ilkinbildirim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField muddet;
    private javax.swing.JLabel muddetbildirim;
    private javax.swing.JTextField qiymet;
    private javax.swing.JLabel qiymetbildirim;
    private javax.swing.JButton sil;
    private javax.swing.JTextArea textarea;
    // End of variables declaration//GEN-END:variables

}
